<!doctype html>
<html lang="en" class="dark">
<head>
  <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{{ $mode === 'login' ? 'Welcome back' : ($mode === 'register' ? 'Create your free account' : 'Account recovery') }} · SmartCV</title>
  @vite(['resources/css/app.css', 'resources/js/app.js'])
</head>
<body class="min-h-screen bg-ink text-zinc-100">
  <div class="noise pointer-events-none fixed inset-0 opacity-[.025]"></div>
  <div class="fixed -left-36 -top-36 h-96 w-96 rounded-full bg-indigo-500/20 blur-[130px]"></div>
  <div class="fixed -bottom-48 -right-36 h-96 w-96 rounded-full bg-cyan-400/15 blur-[130px]"></div>
  <main class="relative mx-auto grid min-h-screen max-w-6xl place-items-center px-5 py-10 lg:grid-cols-[1.1fr_.9fr] lg:gap-16">
    <section class="hidden max-w-lg lg:block"><a href="/" class="inline-flex items-center gap-2.5"><span class="grid h-9 w-9 place-items-center rounded-xl bg-gradient-to-br from-indigo-400 to-cyan-500 font-bold shadow-lg shadow-cyan-950/30">✦</span><span class="text-sm font-bold tracking-tight">SMART<span class="text-cyan-300">CV</span></span></a><p class="eyebrow mt-12">Free forever</p><h1 class="mt-4 text-5xl font-semibold leading-[1.02] tracking-[-.05em]">Build a career with<br><span class="bg-gradient-to-r from-indigo-300 to-cyan-300 bg-clip-text text-transparent">real momentum.</span></h1><p class="mt-6 max-w-md text-base leading-7 text-slate-400">Your private workspace for stronger resumes, focused applications, and confident interviews—without a paywall.</p><div class="mt-10 flex items-center gap-4 text-xs text-slate-400"><span>✓ No credit card</span><span>✓ Private by default</span><span>✓ Free career tools</span></div></section>
    <section class="card glow w-full max-w-md p-6 sm:p-8"><a href="/" class="mb-8 flex items-center gap-2.5 lg:hidden"><span class="grid h-8 w-8 place-items-center rounded-xl bg-gradient-to-br from-indigo-400 to-cyan-500">✦</span><span class="text-sm font-bold">SMART<span class="text-cyan-300">CV</span></span></a>
      @if(session('status'))<div class="mb-5 rounded-xl border border-emerald-400/20 bg-emerald-400/10 p-3 text-sm text-emerald-200">{{ session('status') }}</div>@endif
      @if(session('error'))<div class="mb-5 rounded-xl border border-rose-400/20 bg-rose-400/10 p-3 text-sm text-rose-200">{{ session('error') }}</div>@endif
      @if($mode === 'login')
        <p class="eyebrow">Welcome back</p><h2 class="mt-3 text-2xl font-semibold">Continue your career journey.</h2><p class="mt-2 text-sm text-slate-400">Sign in to your private SmartCV workspace.</p>
        <form method="POST" action="{{ route('login.store') }}" class="mt-7 space-y-4">@csrf<label class="block text-xs text-slate-400">Email address<input class="input mt-2" type="email" name="email" value="{{ old('email') }}" autocomplete="email" required autofocus></label><label class="block text-xs text-slate-400">Password<input class="input mt-2" type="password" name="password" autocomplete="current-password" required></label><div class="flex items-center justify-between text-xs"><label class="flex items-center gap-2 text-slate-400"><input type="checkbox" name="remember" class="accent-cyan-400"> Keep me signed in</label><a href="{{ route('password.request') }}" class="text-cyan-300 hover:text-cyan-200">Forgot password?</a></div><button class="btn btn-primary w-full py-3">Sign in →</button></form><p class="mt-6 text-center text-sm text-slate-400">New to SmartCV? <a href="{{ route('register') }}" class="font-medium text-cyan-300">Create a free account</a></p>
      @elseif($mode === 'register')
        <p class="eyebrow">Free forever</p><h2 class="mt-3 text-2xl font-semibold">Create your career workspace.</h2><p class="mt-2 text-sm text-slate-400">No credit card. No trial ending. Just your next best move.</p>
        <form method="POST" action="{{ route('register.store') }}" class="mt-7 space-y-4">@csrf<label class="block text-xs text-slate-400">Your name<input class="input mt-2" type="text" name="name" value="{{ old('name') }}" autocomplete="name" required autofocus></label><label class="block text-xs text-slate-400">Email address<input class="input mt-2" type="email" name="email" value="{{ old('email') }}" autocomplete="email" required></label><label class="block text-xs text-slate-400">Password<input class="input mt-2" type="password" name="password" autocomplete="new-password" required></label><label class="block text-xs text-slate-400">Confirm password<input class="input mt-2" type="password" name="password_confirmation" autocomplete="new-password" required></label><button class="btn btn-primary w-full py-3">Create free account →</button></form><p class="mt-6 text-center text-sm text-slate-400">Already have an account? <a href="{{ route('login') }}" class="font-medium text-cyan-300">Sign in</a></p>
      @elseif($mode === 'forgot')
        <p class="eyebrow">Account recovery</p><h2 class="mt-3 text-2xl font-semibold">Reset your password.</h2><p class="mt-2 text-sm text-slate-400">Enter your email and we will send a secure reset link.</p><form method="POST" action="{{ route('password.email') }}" class="mt-7 space-y-4">@csrf<label class="block text-xs text-slate-400">Email address<input class="input mt-2" type="email" name="email" value="{{ old('email') }}" autocomplete="email" required autofocus></label><button class="btn btn-primary w-full py-3">Send reset link</button></form><p class="mt-6 text-center text-sm"><a href="{{ route('login') }}" class="text-cyan-300">← Back to sign in</a></p>
      @else
        <p class="eyebrow">Choose a new password</p><h2 class="mt-3 text-2xl font-semibold">Secure your workspace.</h2><form method="POST" action="{{ route('password.update') }}" class="mt-7 space-y-4">@csrf<input type="hidden" name="token" value="{{ $token }}"><label class="block text-xs text-slate-400">Email address<input class="input mt-2" type="email" name="email" value="{{ old('email', $email) }}" autocomplete="email" required></label><label class="block text-xs text-slate-400">New password<input class="input mt-2" type="password" name="password" autocomplete="new-password" required></label><label class="block text-xs text-slate-400">Confirm new password<input class="input mt-2" type="password" name="password_confirmation" autocomplete="new-password" required></label><button class="btn btn-primary w-full py-3">Reset password</button></form>
      @endif
      @if($errors->any())<div class="mt-5 rounded-xl border border-rose-400/20 bg-rose-400/10 p-3 text-sm text-rose-200"><ul class="space-y-1">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    </section>
  </main>
</body></html>
