<!doctype html>
<html lang="en" class="dark"><head>
  <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="Smart Resume Analyzer — the intelligent career operating system for ambitious professionals.">
  <title>Smart Resume Analyzer — Your career, intelligently accelerated.</title>
  @vite(['resources/css/app.css','resources/js/app.js'])
</head>
<body class="overflow-x-hidden">
  <div class="fixed inset-0 -z-20 grid-bg opacity-30"></div><div class="noise fixed inset-0 -z-10 opacity-[.025]"></div>
  <div class="pointer-events-none fixed -top-64 left-1/2 -z-10 h-[42rem] w-[42rem] -translate-x-1/2 rounded-full bg-violet-700/20 blur-[140px]"></div>
  <header class="sticky top-0 z-40 border-b border-white/[.07] bg-[#060609]/75 backdrop-blur-xl">
    <div class="mx-auto flex h-18 max-w-7xl items-center justify-between px-5 lg:px-8">
      <a href="/" class="flex items-center gap-2.5"><span class="grid h-8 w-8 place-items-center rounded-xl bg-gradient-to-br from-violet-300 to-violet-700 shadow-lg shadow-violet-900/40"><svg class="h-4 w-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><path d="M6 3v18M18 3v18M6 12h12"/><path d="m14 7 4 5-4 5"/></svg></span><span class="text-sm font-bold tracking-tight">SMART<span class="text-violet-400">CV</span></span></a>
      <nav class="hidden items-center gap-7 text-sm text-zinc-400 md:flex"><a href="#platform" class="hover:text-white">Platform</a><a href="#how" class="hover:text-white">How it works</a><a href="#security" class="hover:text-white">Security</a><a href="/pricing" class="hover:text-white">Pricing</a></nav>
      <div class="flex items-center gap-3"><a href="/dashboard" class="hidden text-sm text-zinc-300 hover:text-white sm:block">Sign in</a><a href="/dashboard" class="btn btn-primary px-4">Start for free <span>→</span></a></div>
    </div>
  </header>
  <main>
    <section class="relative mx-auto max-w-7xl px-5 pb-20 pt-20 text-center lg:px-8 lg:pb-28 lg:pt-28">
      <div class="mx-auto mb-7 inline-flex items-center gap-2 rounded-full border border-violet-400/20 bg-violet-400/[.07] px-3 py-1.5 text-xs text-violet-200"><span class="pulse-dot h-1.5 w-1.5 rounded-full bg-violet-400"></span> AI career intelligence, built for serious professionals</div>
      <h1 class="mx-auto max-w-5xl text-5xl font-semibold leading-[.98] tracking-[-.055em] text-white sm:text-6xl lg:text-8xl">Your next career move,<br><span class="bg-gradient-to-r from-violet-300 via-purple-400 to-fuchsia-300 bg-clip-text text-transparent">made unmistakably clear.</span></h1>
      <p class="mx-auto mt-7 max-w-2xl text-base leading-7 text-zinc-400 sm:text-lg">Turn your experience into opportunity. SmartCV analyzes your resume, strengthens every application, and gives you the confidence to show up prepared.</p>
      <div class="mt-9 flex flex-col justify-center gap-3 sm:flex-row"><a href="/dashboard" class="btn btn-primary px-6 py-3 text-sm">Analyze my resume <span>→</span></a><a href="#platform" class="btn btn-secondary px-6 py-3 text-sm">Explore the platform</a></div>
      <p class="mt-4 text-xs text-zinc-600">No credit card required · Free analysis included</p>
      <div class="relative mx-auto mt-16 max-w-5xl rounded-[28px] border border-white/[.12] bg-gradient-to-b from-[#191524] to-[#0b0b11] p-2 shadow-2xl shadow-violet-950/30">
        <div class="overflow-hidden rounded-[22px] border border-white/[.07] bg-[#0c0c12] text-left">
          <div class="flex h-11 items-center gap-2 border-b border-white/[.07] px-4"><i class="h-2.5 w-2.5 rounded-full bg-red-400/70"></i><i class="h-2.5 w-2.5 rounded-full bg-amber-300/70"></i><i class="h-2.5 w-2.5 rounded-full bg-emerald-400/70"></i><div class="mx-auto rounded-md bg-white/[.04] px-12 py-1 text-[10px] text-zinc-600">app.smartcv.ai/dashboard</div></div>
          <div class="grid min-h-[340px] grid-cols-[145px_1fr] sm:min-h-[420px] sm:grid-cols-[190px_1fr]">
            <div class="border-r border-white/[.07] p-3 sm:p-5"><div class="mb-7 flex items-center gap-1.5 text-[9px] font-bold sm:text-xs"><span class="h-5 w-5 rounded-md bg-violet-500"></span> SMART<span class="text-violet-400">CV</span></div><div class="space-y-2 text-[9px] text-zinc-500 sm:text-xs"><div class="rounded-md bg-violet-400/15 px-2 py-2 text-violet-200">◈ Overview</div><div class="px-2 py-1.5">▤ My resumes</div><div class="px-2 py-1.5">◎ Job tracker</div><div class="px-2 py-1.5">◌ Interview lab</div><div class="px-2 py-1.5">⌁ Insights</div></div></div>
            <div class="p-5 sm:p-8"><div class="flex justify-between"><div><p class="text-[10px] text-zinc-500 sm:text-xs">Thursday, July 19</p><h2 class="mt-1 text-lg font-semibold sm:text-2xl">Good morning, Noah.</h2></div><span class="hidden h-8 w-8 rounded-full bg-gradient-to-br from-amber-200 to-violet-500 sm:block"></span></div><div class="mt-6 grid gap-3 sm:grid-cols-3"><div class="rounded-xl border border-violet-300/20 bg-violet-500/[.08] p-3 sm:p-4"><p class="text-[9px] text-violet-200 sm:text-xs">Career strength</p><p class="mt-2 text-2xl font-semibold sm:text-3xl">82<span class="text-sm text-violet-300">/100</span></p><div class="mt-3 h-1 rounded bg-white/10"><div class="h-1 w-[82%] rounded bg-violet-400"></div></div></div><div class="rounded-xl border border-white/[.08] p-3 sm:p-4"><p class="text-[9px] text-zinc-500 sm:text-xs">Applications</p><p class="mt-2 text-2xl font-semibold sm:text-3xl">14</p><p class="mt-3 text-[9px] text-emerald-400">↑ 3 this week</p></div><div class="hidden rounded-xl border border-white/[.08] p-4 sm:block"><p class="text-xs text-zinc-500">Interview readiness</p><p class="mt-2 text-3xl font-semibold">76<span class="text-sm text-zinc-500">%</span></p><p class="mt-3 text-[9px] text-amber-300">2 skills to improve</p></div></div><div class="mt-4 rounded-xl border border-white/[.08] p-4"><div class="flex justify-between text-[10px] sm:text-xs"><span class="font-medium">Your application momentum</span><span class="text-violet-300">Last 30 days</span></div><svg class="mt-3 h-20 w-full" viewBox="0 0 500 90" preserveAspectRatio="none"><defs><linearGradient id="a" x1="0" x2="0" y1="0" y2="1"><stop stop-color="#8b5cf6" stop-opacity=".35"/><stop offset="1" stop-color="#8b5cf6" stop-opacity="0"/></linearGradient></defs><path d="M0 73 C35 63,48 75,77 56 S129 65,160 49 S211 55,237 32 S286 54,318 39 S370 27,400 42 S442 19,500 12 V90 H0Z" fill="url(#a)"/><path d="M0 73 C35 63,48 75,77 56 S129 65,160 49 S211 55,237 32 S286 54,318 39 S370 27,400 42 S442 19,500 12" fill="none" stroke="#a78bfa" stroke-width="2"/></svg></div></div>
          </div>
        </div>
      </div>
    </section>
    <section class="border-y border-white/[.06] bg-white/[.02] py-10"><p class="text-center text-xs font-medium uppercase tracking-[.2em] text-zinc-600">Built for professionals shaping what’s next</p><div class="mx-auto mt-6 flex max-w-5xl flex-wrap items-center justify-center gap-x-12 gap-y-5 text-lg font-bold tracking-tight text-zinc-600 sm:gap-x-20"><span>vertex</span><span>northstar</span><span>mosaic</span><span>ALTO</span><span>cloudline</span></div></section>
    <section id="platform" class="mx-auto max-w-7xl px-5 py-24 lg:px-8"><div class="max-w-2xl"><p class="eyebrow">One intelligent workspace</p><h2 class="mt-4 text-4xl font-semibold tracking-[-.04em] sm:text-5xl">Every signal. One clear path forward.</h2><p class="mt-5 text-zinc-400">A connected set of tools that helps you make better career decisions — from your first draft to your final offer.</p></div><div class="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-3">
      @foreach ([['✦','Resume intelligence','Find what recruiters see, fix what ATS systems miss, and turn your experience into a compelling story.'],['⌘','Job command center','Organize every opportunity, follow-up, contact, and interview in one calm workspace.'],['◉','Interview lab','Practice with AI-guided simulations and receive precise, actionable feedback.'],['↗','Career insights','See your strongest signals, skill gaps, market fit, and the moves that will create momentum.'],['◇','Portfolio studio','Build a polished professional presence that lets your best work speak first.'],['∿','Growth plan','Build an adaptive learning plan based on where you are and where you want to go.']] as [$icon,$title,$text])
        <article class="card card-hover p-6"><div class="grid h-10 w-10 place-items-center rounded-xl border border-violet-300/20 bg-violet-400/10 text-lg text-violet-300">{{ $icon }}</div><h3 class="mt-5 font-semibold">{{ $title }}</h3><p class="mt-2 text-sm leading-6 text-zinc-400">{{ $text }}</p><a href="/dashboard" class="mt-5 inline-flex text-sm text-violet-300 hover:text-violet-200">Explore tool <span class="ml-2">→</span></a></article>
      @endforeach
    </div></section>
    <section id="how" class="mx-auto max-w-7xl px-5 py-20 lg:px-8"><div class="card overflow-hidden p-7 md:p-12"><div class="grid items-center gap-12 lg:grid-cols-2"><div><p class="eyebrow">Designed around your progress</p><h2 class="mt-4 text-3xl font-semibold tracking-[-.04em] sm:text-4xl">A smarter rhythm for your career.</h2><div class="mt-9 space-y-6">@foreach ([['01','Tell us where you’re headed','Upload a resume or start with a role you want to pursue.'],['02','See the path clearly','Your workspace turns your career data into practical next steps.'],['03','Make better moves','Prepare, apply, learn, and grow with every action connected.']] as [$number,$title,$text])<div class="flex gap-4"><span class="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-violet-400/10 text-xs font-bold text-violet-300">{{ $number }}</span><div><h3 class="text-sm font-semibold">{{ $title }}</h3><p class="mt-1 text-sm text-zinc-400">{{ $text }}</p></div></div>@endforeach</div></div><div class="relative rounded-2xl border border-white/[.08] bg-black/30 p-5"><div class="absolute -right-6 -top-6 h-28 w-28 rounded-full bg-violet-600/20 blur-3xl"></div><p class="text-xs text-zinc-500">Next best action</p><h3 class="mt-2 text-xl font-semibold">Tailor your resume for the<br>Senior Product Designer role</h3><div class="mt-6 rounded-xl border border-white/[.09] bg-white/[.04] p-4"><div class="flex items-center justify-between"><span class="text-sm">Role match</span><span class="font-semibold text-emerald-400">+18 points</span></div><div class="mt-3 h-2 overflow-hidden rounded-full bg-white/10"><div class="h-full w-[86%] rounded-full bg-gradient-to-r from-violet-500 to-fuchsia-400"></div></div><div class="mt-4 flex items-center gap-2 text-xs text-zinc-400"><span class="h-2 w-2 rounded-full bg-emerald-400"></span> 3 high-impact updates identified</div></div><button data-open-modal class="btn btn-primary mt-5 w-full">View recommendation</button></div></div></div>
    </section>
    <section id="security" class="border-y border-white/[.06] bg-white/[.02] px-5 py-20 text-center"><p class="eyebrow">Privacy is part of the product</p><h2 class="mx-auto mt-4 max-w-2xl text-3xl font-semibold tracking-[-.04em] sm:text-4xl">Your career story stays yours.</h2><p class="mx-auto mt-4 max-w-xl text-sm leading-6 text-zinc-400">Your documents are protected with enterprise-grade safeguards. We never sell your personal information or train public models on your resume.</p><div class="mx-auto mt-8 flex max-w-2xl flex-wrap justify-center gap-3 text-xs text-zinc-300"><span class="rounded-full border border-white/10 px-4 py-2">◈ Encrypted in transit & at rest</span><span class="rounded-full border border-white/10 px-4 py-2">◈ You control your data</span><span class="rounded-full border border-white/10 px-4 py-2">◈ Built for privacy</span></div></section>
    <section class="mx-auto max-w-4xl px-5 py-28 text-center"><p class="eyebrow">Your career deserves momentum</p><h2 class="mt-4 text-4xl font-semibold tracking-[-.05em] sm:text-6xl">Make your next move<br>your best one.</h2><p class="mx-auto mt-5 max-w-xl text-zinc-400">Join thousands of professionals building a clearer, more confident career path.</p><a href="/dashboard" class="btn btn-primary mt-8 px-6 py-3">Build your career workspace <span>→</span></a></section>
  </main>
  <footer class="border-t border-white/[.07] px-5 py-9"><div class="mx-auto flex max-w-7xl flex-col items-center justify-between gap-4 text-xs text-zinc-600 sm:flex-row"><div class="flex items-center gap-2 font-semibold text-zinc-400"><span class="text-violet-400">✦</span> SMARTCV</div><div class="flex gap-5"><a href="/privacy" class="hover:text-zinc-300">Privacy</a><a href="/terms" class="hover:text-zinc-300">Terms</a><a href="/help" class="hover:text-zinc-300">Help center</a></div><span>© {{ date('Y') }} SmartCV, Inc.</span></div></footer>
  <div data-modal class="fixed inset-0 z-50 hidden place-items-center bg-black/70 p-4 backdrop-blur-sm"><div class="card glow w-full max-w-md p-6"><div class="flex items-start justify-between"><div><p class="eyebrow">Smart recommendation</p><h3 class="mt-2 text-xl font-semibold">Make your impact visible.</h3></div><button data-close-modal class="text-zinc-500 hover:text-white">✕</button></div><p class="mt-4 text-sm leading-6 text-zinc-400">Your resume has strong experience. Adding measurable outcomes to two recent roles could increase your match score by 18 points.</p><a href="/analyze" class="btn btn-primary mt-6 w-full">Open resume studio</a></div></div>
</body></html>
