<!doctype html>
<html lang="en" class="dark">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Document vault · SmartCV</title>@vite(['resources/css/app.css', 'resources/js/app.js'])</head>
<body class="min-h-screen bg-[#070b18] text-zinc-100"><div class="min-h-screen"><x-workspace-sidebar active-screen="documents" />
<div class="min-h-screen lg:pl-64"><header class="sticky top-0 z-20 flex items-center justify-between border-b border-white/[.07] bg-[#090e20]/95 px-5 py-4 backdrop-blur lg:px-9"><a href="{{ route('dashboard') }}" class="font-bold lg:hidden">SMART<span class="text-violet-300">CV</span></a><span class="hidden text-sm text-zinc-500 sm:block">Private documents and readable text previews</span><a href="{{ route('profile') }}" class="text-sm font-medium">{{ auth()->user()->name }}</a></header>
<main class="mx-auto max-w-7xl px-5 py-8 lg:px-9"><p class="eyebrow">Private workspace</p><h1 class="mt-2 text-3xl font-semibold tracking-tight">Document vault</h1><p class="mt-2 max-w-3xl text-sm leading-6 text-zinc-400">Store career documents privately, extract text from supported PDF, DOCX, and TXT files, and download them whenever you need them.</p>
@if(session('status'))<div class="mt-6 rounded-xl border border-emerald-400/25 bg-emerald-400/10 p-4 text-sm text-emerald-100">{{ session('status') }}</div>@endif
@if($errors->any())<div class="mt-6 rounded-xl border border-rose-400/25 bg-rose-400/10 p-4 text-sm text-rose-100"><ul class="list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<section class="mt-7 grid gap-5 xl:grid-cols-[360px_minmax(0,1fr)]"><aside class="card h-max p-5"><p class="eyebrow">Secure upload</p><h2 class="mt-2 text-lg font-semibold">Add a private document</h2><p class="mt-2 text-sm leading-6 text-zinc-400">Files are stored outside the public web folder. Only your account can download them.</p><form method="POST" action="{{ route('documents.store') }}" enctype="multipart/form-data" class="mt-5 space-y-4">@csrf<label class="block text-xs text-zinc-400">Display name <span class="text-zinc-600">(optional)</span><input class="input mt-2" name="name" placeholder="AWS certificate"></label><label class="block text-xs text-zinc-400">File<input class="input mt-2" type="file" name="document" accept=".pdf,.doc,.docx,.txt,.png,.jpg,.jpeg,.webp" required></label><p class="text-xs leading-5 text-zinc-600">PDF, DOC, DOCX, TXT, and image files up to 10 MB. Text previews are available for text-based PDFs, DOCX, and TXT.</p><button class="btn btn-primary w-full">Upload privately</button></form></aside>
<div class="space-y-4">@forelse($documents as $document)<article class="card p-5"><div class="flex flex-col justify-between gap-4 sm:flex-row"><div class="min-w-0"><div class="flex items-center gap-3"><span class="rounded-lg border border-cyan-400/20 bg-cyan-400/[.08] px-2 py-1 text-xs font-bold text-cyan-100">{{ $document->extensionLabel() }}</span><h2 class="truncate font-semibold">{{ $document->name }}</h2></div><p class="mt-2 text-sm text-zinc-400">{{ $document->original_filename }} · {{ number_format($document->file_size / 1024, 1) }} KB · {{ $document->created_at->diffForHumans() }}</p></div><div class="flex shrink-0 gap-3"><a href="{{ route('documents.download', $document) }}" class="btn btn-secondary">Download</a><form method="POST" action="{{ route('documents.destroy', $document) }}" onsubmit="return confirm('Remove this private document? This cannot be undone.')">@csrf @method('DELETE')<button class="btn btn-secondary !border-rose-400/30 !text-rose-200">Remove</button></form></div></div>@if($document->extracted_text)<details class="mt-5 rounded-xl border border-white/[.08] p-4"><summary class="cursor-pointer text-sm font-medium text-cyan-100">Read extracted text preview</summary><p class="mt-4 max-h-64 overflow-y-auto whitespace-pre-wrap text-sm leading-6 text-zinc-400">{{ $document->extracted_text }}</p></details>@else<p class="mt-4 text-xs text-zinc-600">No readable text preview is available for this file. You can still download it privately.</p>@endif</article>@empty<article class="card border-dashed p-10 text-center"><h2 class="font-semibold">Your vault is empty</h2><p class="mt-2 text-sm text-zinc-500">Add certificates, work samples, notes, or other private career documents.</p></article>@endforelse</div></section></main></div></div></body></html>
