<!doctype html>
<html lang="en" class="dark">
<head>
  <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{{ $resume ? 'Edit '.$resume->name : 'Create resume' }} · SmartCV</title>
  @vite(['resources/css/app.css', 'resources/js/app.js'])
  <style>.builder-shell{max-width:1500px}.builder-card{border:1px solid rgba(255,255,255,.09);background:rgba(13,19,38,.86);border-radius:18px}.builder-section{border:1px solid rgba(255,255,255,.08);border-radius:14px;padding:16px}.preview-note{background:linear-gradient(135deg,rgba(124,58,237,.14),rgba(34,211,238,.08))}</style>
</head>
<body class="min-h-screen bg-[#070b18] text-zinc-100">
@php
  $personal = $content['personal']; $settings = $content['settings'];
  $collections = ['experience' => $content['experience'], 'education' => $content['education'], 'projects' => $content['projects'], 'certifications' => $content['certifications'], 'awards' => $content['awards'], 'languages' => $content['languages'], 'custom_sections' => $content['custom_sections']];
@endphp
<header class="sticky top-0 z-30 border-b border-white/[.08] bg-[#090e20]/95 backdrop-blur"><div class="mx-auto flex max-w-[1500px] items-center justify-between gap-3 px-4 py-4 sm:px-7"><a href="{{ route('resumes') }}" class="text-sm font-semibold text-zinc-300">← My resumes</a><div class="hidden text-sm text-zinc-500 sm:block">Private resume builder</div><div class="flex gap-2">@if($resume)<a class="btn btn-secondary" target="_blank" href="{{ route('resumes.preview', $resume) }}">Preview / PDF</a><a class="btn btn-secondary" href="{{ route('resumes.export.docx', $resume) }}">Export DOCX</a>@endif</div></div></header>
<main class="builder-shell mx-auto px-4 py-7 sm:px-7">
  <div class="mb-7 flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><p class="eyebrow">Resume builder</p><h1 class="mt-2 text-3xl font-semibold tracking-tight">{{ $resume ? $resume->name : 'Build a resume from scratch' }}</h1><p class="mt-2 text-sm text-zinc-400">Every save is private to your account. Create a focused version for each opportunity.</p></div>@if($resume)<div class="flex flex-wrap gap-2"><form method="POST" action="{{ route('resumes.duplicate', $resume) }}">@csrf<button class="btn btn-secondary">Duplicate</button></form><form method="POST" action="{{ route('resumes.versions.store', $resume) }}" class="flex gap-2">@csrf<input class="input !w-40 !py-2 text-xs" name="label" placeholder="Version label" required><button class="btn btn-secondary">Save new version</button></form></div>@endif</div>
  @if(session('status'))<div class="mb-5 rounded-xl border border-emerald-400/25 bg-emerald-400/10 p-4 text-sm text-emerald-100">{{ session('status') }}</div>@endif
  @if($errors->any())<div class="mb-5 rounded-xl border border-rose-400/25 bg-rose-400/10 p-4 text-sm text-rose-100"><ul class="list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
  <form method="POST" action="{{ $resume ? route('resumes.builder.update', $resume) : route('resumes.builder.store') }}" class="grid gap-5 xl:grid-cols-[minmax(0,1fr)_330px]" @if($resume) data-autosave @endif>
    @csrf @if($resume) @method('PATCH') @endif
    <div class="space-y-5">
      <section class="builder-card p-5 sm:p-6"><div class="flex items-center justify-between gap-3"><div><p class="eyebrow">Foundation</p><h2 class="mt-1 text-xl font-semibold">Resume details</h2></div><span class="rounded-full bg-violet-400/10 px-3 py-1 text-xs text-violet-200">{{ $resume ? 'Autosaves after changes' : 'Save to start autosave' }}</span></div><div class="mt-5 grid gap-4 sm:grid-cols-2"><label class="text-xs text-zinc-400 sm:col-span-2">Resume name<input name="name" class="input mt-1" required value="{{ old('name', $resume?->name) }}" placeholder="Product designer — 2026"></label><label class="text-xs text-zinc-400">Version label<input name="version_label" class="input mt-1" value="{{ old('version_label', $resume?->currentVersion()?->label ?: 'Working draft') }}"></label><label class="text-xs text-zinc-400">Template<select name="template" class="input mt-1"><option value="classic" @selected($settings['template']==='classic')>Classic ATS</option><option value="modern" @selected($settings['template']==='modern')>Modern</option><option value="executive" @selected($settings['template']==='executive')>Executive</option></select></label></div></section>
      <section class="builder-card p-5 sm:p-6"><p class="eyebrow">Identity</p><h2 class="mt-1 text-xl font-semibold">Personal information</h2><div class="mt-5 grid gap-4 sm:grid-cols-2">@foreach(['name'=>'Full name','email'=>'Email','phone'=>'Phone','location'=>'Location','website'=>'Website','linkedin'=>'LinkedIn URL'] as $key => $label)<label class="text-xs text-zinc-400">{{ $label }}<input name="personal[{{ $key }}]" class="input mt-1" value="{{ old('personal.'.$key, $personal[$key] ?? '') }}"></label>@endforeach</div></section>
      <section class="builder-card p-5 sm:p-6"><p class="eyebrow">Your pitch</p><h2 class="mt-1 text-xl font-semibold">Professional summary</h2><textarea name="summary" class="input mt-5 h-36 resize-y" placeholder="Write 3–5 lines about the value you bring.">{{ old('summary', $content['summary']) }}</textarea></section>

      @foreach($collections as $collection => $items)
        @php $labels = ['experience'=>['Experience','Title','Company','Location','Start','End','Highlights — one achievement per line'], 'education'=>['Education','Degree / qualification','School','Location','Start','End','Details'], 'projects'=>['Projects','Project name','Your role','Project link','Details'], 'certifications'=>['Certifications','Certification name','Issuer','Date'], 'awards'=>['Awards','Award name','Issuer','Date'], 'languages'=>['Languages','Language','Level'], 'custom_sections'=>['Custom sections','Section title','Content']]; $fields = $labels[$collection]; @endphp
        <section class="builder-card p-5 sm:p-6" data-collection="{{ $collection }}"><div class="flex items-center justify-between gap-3"><div><p class="eyebrow">{{ $fields[0] }}</p><h2 class="mt-1 text-xl font-semibold">{{ $fields[0] }}</h2></div><button type="button" class="btn btn-secondary text-xs" data-add="{{ $collection }}">+ Add</button></div><div class="mt-5 space-y-3" data-items="{{ $collection }}">
          @forelse($items as $index => $item)
            <div class="builder-section" data-item><div class="mb-3 flex justify-end"><button type="button" class="text-xs text-rose-200" data-remove>Remove</button></div>
              @if($collection === 'experience')<div class="grid gap-3 sm:grid-cols-2"><label class="text-xs text-zinc-400">Title<input class="input mt-1" name="experience[{{ $index }}][title]" value="{{ $item['title'] ?? '' }}"></label><label class="text-xs text-zinc-400">Company<input class="input mt-1" name="experience[{{ $index }}][company]" value="{{ $item['company'] ?? '' }}"></label><label class="text-xs text-zinc-400">Location<input class="input mt-1" name="experience[{{ $index }}][location]" value="{{ $item['location'] ?? '' }}"></label><label class="text-xs text-zinc-400">Dates<input class="input mt-1" name="experience[{{ $index }}][start]" value="{{ $item['start'] ?? '' }}" placeholder="Jan 2024"><input class="input mt-2" name="experience[{{ $index }}][end]" value="{{ $item['end'] ?? '' }}" placeholder="Present"></label><label class="text-xs text-zinc-400 sm:col-span-2">Highlights<textarea class="input mt-1 h-28" name="experience[{{ $index }}][highlights_text]">{{ implode("\n", $item['highlights'] ?? []) }}</textarea></label></div>
              @elseif($collection === 'education')<div class="grid gap-3 sm:grid-cols-2">@foreach(['degree'=>'Degree / qualification','school'=>'School','location'=>'Location','start'=>'Start','end'=>'End','details'=>'Details'] as $key=>$label)<label class="text-xs text-zinc-400 {{ $key==='details' ? 'sm:col-span-2' : '' }}">{{ $label }}@if($key==='details')<textarea class="input mt-1 h-20" name="education[{{ $index }}][{{ $key }}]">{{ $item[$key] ?? '' }}</textarea>@else<input class="input mt-1" name="education[{{ $index }}][{{ $key }}]" value="{{ $item[$key] ?? '' }}">@endif</label>@endforeach</div>
              @elseif(in_array($collection, ['projects','custom_sections'], true))<div class="grid gap-3 sm:grid-cols-2">@foreach($collection==='projects'?['name'=>'Project name','role'=>'Your role','link'=>'Project link','details'=>'Details']:['title'=>'Section title','content'=>'Content'] as $key=>$label)<label class="text-xs text-zinc-400 {{ in_array($key,['details','content'],true) ? 'sm:col-span-2' : '' }}">{{ $label }}@if(in_array($key,['details','content'],true))<textarea class="input mt-1 h-24" name="{{ $collection }}[{{ $index }}][{{ $key }}]">{{ $item[$key] ?? '' }}</textarea>@else<input class="input mt-1" name="{{ $collection }}[{{ $index }}][{{ $key }}]" value="{{ $item[$key] ?? '' }}">@endif</label>@endforeach</div>
              @else<div class="grid gap-3 sm:grid-cols-3">@foreach($collection==='languages'?['name'=>'Language','level'=>'Level']:['name'=>$fields[1],'issuer'=>$fields[2],'date'=>$fields[3]] as $key=>$label)<label class="text-xs text-zinc-400">{{ $label }}<input class="input mt-1" name="{{ $collection }}[{{ $index }}][{{ $key }}]" value="{{ $item[$key] ?? '' }}"></label>@endforeach</div>@endif
            </div>
          @empty <p class="rounded-xl border border-dashed border-white/[.1] p-4 text-sm text-zinc-500" data-empty>Nothing added yet. Use “Add” when this section strengthens your story.</p> @endforelse
        </div></section>
      @endforeach
      <section class="builder-card p-5 sm:p-6"><p class="eyebrow">Skills and interests</p><h2 class="mt-1 text-xl font-semibold">Strengths at a glance</h2><div class="mt-5 grid gap-4 sm:grid-cols-2"><label class="text-xs text-zinc-400">Skills, separated by commas<input name="skills" class="input mt-1" value="{{ old('skills', implode(', ', $content['skills'])) }}" placeholder="Laravel, UX research, SQL"></label><label class="text-xs text-zinc-400">Interests, separated by commas<input name="interests" class="input mt-1" value="{{ old('interests', implode(', ', $content['interests'])) }}" placeholder="Running, accessibility, photography"></label></div></section>
    </div>
    <aside class="space-y-5"><section class="builder-card sticky top-24 p-5"><p class="eyebrow">Design controls</p><h2 class="mt-1 text-lg font-semibold">Make it yours</h2><div class="mt-5 space-y-4"><label class="block text-xs text-zinc-400">Accent color<input type="color" name="accent_color" class="mt-2 block h-11 w-full rounded-lg border border-white/[.08] bg-transparent p-1" value="{{ $settings['accent_color'] }}"></label><label class="block text-xs text-zinc-400">Font family<select name="font_family" class="input mt-1"><option @selected($settings['font_family']==='Inter')>Inter</option><option @selected($settings['font_family']==='Georgia')>Georgia</option><option @selected($settings['font_family']==='Arial')>Arial</option></select></label><label class="block text-xs text-zinc-400">Length<select name="page_length" class="input mt-1"><option value="one" @selected($settings['page_length']==='one')>One page</option><option value="two" @selected($settings['page_length']==='two')>Two pages</option></select></label></div><div class="preview-note mt-5 rounded-xl p-4 text-xs leading-5 text-zinc-300">Choose a template without losing any writing. Open Preview to print or choose “Save as PDF” in your browser.</div><button class="btn btn-primary mt-5 w-full">{{ $resume ? 'Save resume' : 'Create resume' }}</button>@if($resume)<a class="btn btn-secondary mt-2 w-full" target="_blank" href="{{ route('resumes.preview', $resume) }}">Preview current saved version</a>@endif</section></aside>
  </form>
</main>
<template id="experience-template"><div class="builder-section" data-item><div class="mb-3 flex justify-end"><button type="button" class="text-xs text-rose-200" data-remove>Remove</button></div><div class="grid gap-3 sm:grid-cols-2"><label class="text-xs text-zinc-400">Title<input class="input mt-1" name="experience[__i__][title]"></label><label class="text-xs text-zinc-400">Company<input class="input mt-1" name="experience[__i__][company]"></label><label class="text-xs text-zinc-400">Location<input class="input mt-1" name="experience[__i__][location]"></label><label class="text-xs text-zinc-400">Dates<input class="input mt-1" name="experience[__i__][start]" placeholder="Jan 2024"><input class="input mt-2" name="experience[__i__][end]" placeholder="Present"></label><label class="text-xs text-zinc-400 sm:col-span-2">Highlights<textarea class="input mt-1 h-28" name="experience[__i__][highlights_text]" placeholder="One achievement per line"></textarea></label></div></div></template>
@foreach(['education'=>'<div class="grid gap-3 sm:grid-cols-2"><label class="text-xs text-zinc-400">Degree / qualification<input class="input mt-1" name="education[__i__][degree]"></label><label class="text-xs text-zinc-400">School<input class="input mt-1" name="education[__i__][school]"></label><label class="text-xs text-zinc-400">Location<input class="input mt-1" name="education[__i__][location]"></label><label class="text-xs text-zinc-400">Start<input class="input mt-1" name="education[__i__][start]"></label><label class="text-xs text-zinc-400">End<input class="input mt-1" name="education[__i__][end]"></label><label class="text-xs text-zinc-400 sm:col-span-2">Details<textarea class="input mt-1 h-20" name="education[__i__][details]"></textarea></label></div>', 'projects'=>'<div class="grid gap-3 sm:grid-cols-2"><label class="text-xs text-zinc-400">Project name<input class="input mt-1" name="projects[__i__][name]"></label><label class="text-xs text-zinc-400">Your role<input class="input mt-1" name="projects[__i__][role]"></label><label class="text-xs text-zinc-400 sm:col-span-2">Project link<input class="input mt-1" name="projects[__i__][link]"></label><label class="text-xs text-zinc-400 sm:col-span-2">Details<textarea class="input mt-1 h-24" name="projects[__i__][details]"></textarea></label></div>', 'certifications'=>'<div class="grid gap-3 sm:grid-cols-3"><label class="text-xs text-zinc-400">Certification name<input class="input mt-1" name="certifications[__i__][name]"></label><label class="text-xs text-zinc-400">Issuer<input class="input mt-1" name="certifications[__i__][issuer]"></label><label class="text-xs text-zinc-400">Date<input class="input mt-1" name="certifications[__i__][date]"></label></div>', 'awards'=>'<div class="grid gap-3 sm:grid-cols-3"><label class="text-xs text-zinc-400">Award name<input class="input mt-1" name="awards[__i__][name]"></label><label class="text-xs text-zinc-400">Issuer<input class="input mt-1" name="awards[__i__][issuer]"></label><label class="text-xs text-zinc-400">Date<input class="input mt-1" name="awards[__i__][date]"></label></div>', 'languages'=>'<div class="grid gap-3 sm:grid-cols-2"><label class="text-xs text-zinc-400">Language<input class="input mt-1" name="languages[__i__][name]"></label><label class="text-xs text-zinc-400">Level<input class="input mt-1" name="languages[__i__][level]"></label></div>', 'custom_sections'=>'<div class="grid gap-3"><label class="text-xs text-zinc-400">Section title<input class="input mt-1" name="custom_sections[__i__][title]"></label><label class="text-xs text-zinc-400">Content<textarea class="input mt-1 h-24" name="custom_sections[__i__][content]"></textarea></label></div>'] as $name=>$html)<template id="{{ $name }}-template"><div class="builder-section" data-item><div class="mb-3 flex justify-end"><button type="button" class="text-xs text-rose-200" data-remove>Remove</button></div>{!! $html !!}</div></template>@endforeach
<script>const form=document.querySelector('[data-autosave]');document.addEventListener('click',e=>{const add=e.target.closest('[data-add]');if(add){const n=add.dataset.add,box=document.querySelector(`[data-items="${n}"]`),tpl=document.getElementById(`${n}-template`);let i=box.querySelectorAll('[data-item]').length;box.querySelector('[data-empty]')?.remove();box.insertAdjacentHTML('beforeend',tpl.innerHTML.replaceAll('__i__',i));form?.dispatchEvent(new Event('input',{bubbles:true}));}if(e.target.matches('[data-remove]')){e.target.closest('[data-item]').remove();form?.dispatchEvent(new Event('input',{bubbles:true}));}});let autosaveTimer;form?.addEventListener('input',()=>{clearTimeout(autosaveTimer);autosaveTimer=setTimeout(async()=>{const data=new FormData(form);data.set('_method','PATCH');try{await fetch(form.action,{method:'POST',body:data,headers:{'X-Requested-With':'XMLHttpRequest'}});document.title=document.title.replace(/^• /,'');}catch(error){document.title=document.title.startsWith('• ')?document.title:'• '+document.title;}},1200);});</script>
</body></html>
