<!doctype html>
<html lang="en" class="dark">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{{ ucfirst($screen) }} · SmartCV</title>
  @vite(['resources/css/app.css', 'resources/js/app.js'])
</head>
<body class="min-h-screen bg-[#070b18] text-zinc-100">
@php
  $nav = ['dashboard' => 'Overview', 'resumes' => 'My resumes', 'jobs' => 'Job tracker', 'interviews' => 'Interview lab', 'skills' => 'Skill studio', 'insights' => 'Career insights', 'portfolio' => 'Portfolio', 'analytics' => 'Analytics'];
  $titles = ['dashboard' => ['Your career workspace', 'A live summary based on your private SmartCV data.'], 'jobs' => ['Job tracker', 'Save every opportunity and keep your next move clear.'], 'interviews' => ['Interview lab', 'Plan focused practice sessions and record your real progress.'], 'skills' => ['Skill studio', 'Build a truthful picture of the skills you are developing.'], 'insights' => ['Career insights', 'Turn your goals and profile into a focused career plan.'], 'portfolio' => ['Portfolio', 'Keep a private, recruiter-ready record of your best work.'], 'analytics' => ['Career analytics', 'Metrics calculated from your saved SmartCV data.'], 'profile' => ['Your profile', 'Keep your professional details current and private.'], 'settings' => ['Settings', 'Manage the information shown in your SmartCV workspace.']];
  [$title, $subtitle] = $titles[$screen];
@endphp
<div class="min-h-screen lg:grid lg:grid-cols-[280px_1fr]">
  <aside class="hidden border-r border-white/[.07] bg-[#090e20] p-5 lg:block">
    <a href="{{ route('dashboard') }}" class="flex items-center gap-3 px-3 py-3 text-lg font-bold"><span class="grid h-9 w-9 place-items-center rounded-xl bg-gradient-to-br from-violet-500 to-cyan-400">S</span> SMART<span class="text-violet-300">CV</span></a>
    <p class="mt-8 px-3 text-[10px] font-bold uppercase tracking-[.18em] text-zinc-600">Workspace</p>
    <nav class="mt-3 space-y-1">@foreach($nav as $route => $label)<a href="/{{ $route }}" class="nav-link {{ $screen === $route ? 'active' : '' }}">{{ $label }}</a>@endforeach</nav>
    <div class="mt-8 border-t border-white/[.07] pt-5"><p class="px-3 text-[10px] font-bold uppercase tracking-[.18em] text-zinc-600">Account</p><a href="{{ route('profile') }}" class="nav-link mt-3 {{ $screen === 'profile' ? 'active' : '' }}">Profile</a><a href="{{ route('settings') }}" class="nav-link {{ $screen === 'settings' ? 'active' : '' }}">Settings</a><form method="POST" action="{{ route('logout') }}">@csrf<button class="nav-link mt-4 w-full text-left">Sign out</button></form></div>
  </aside>
  <div>
    <header class="sticky top-0 z-20 flex items-center justify-between border-b border-white/[.07] bg-[#090e20]/95 px-5 py-4 backdrop-blur lg:px-9"><a href="{{ route('dashboard') }}" class="font-bold lg:hidden">SMART<span class="text-violet-300">CV</span></a><div class="hidden text-sm text-zinc-500 sm:block">Your private career workspace</div><a href="{{ route('profile') }}" class="flex items-center gap-2 text-sm font-medium"><span class="grid h-9 w-9 place-items-center rounded-full bg-gradient-to-br from-violet-400 to-cyan-300 text-slate-950">{{ strtoupper(substr(auth()->user()->name, 0, 1)) }}</span>{{ auth()->user()->name }}</a></header>
    <main class="mx-auto max-w-7xl px-5 py-8 lg:px-9">
      <p class="eyebrow">Career workspace</p><h1 class="mt-2 text-3xl font-semibold tracking-tight">{{ $title }}</h1><p class="mt-2 text-sm text-zinc-400">{{ $subtitle }}</p>
      @if(session('status'))<div class="mt-6 rounded-xl border border-emerald-400/25 bg-emerald-400/10 p-4 text-sm text-emerald-100">{{ session('status') }}</div>@endif
      @if($errors->any())<div class="mt-6 rounded-xl border border-rose-400/25 bg-rose-400/10 p-4 text-sm text-rose-100"><p class="font-semibold">Please check the form.</p><ul class="mt-2 list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif

      @if($screen === 'jobs')
        <section class="mt-7 grid gap-5 xl:grid-cols-[.72fr_1.28fr]"><aside class="card h-max p-5"><h2 class="font-semibold">Add an opportunity</h2><form method="POST" action="{{ route('jobs.store') }}" class="mt-5 space-y-3">@csrf<label class="block text-xs text-zinc-400">Company<input class="input mt-1" name="company" required></label><label class="block text-xs text-zinc-400">Role<input class="input mt-1" name="role" required></label><label class="block text-xs text-zinc-400">Status<select class="input mt-1" name="status">@foreach(['saved','applied','interviewing','offer','rejected','withdrawn'] as $status)<option value="{{ $status }}">{{ ucfirst($status) }}</option>@endforeach</select></label><label class="block text-xs text-zinc-400">Location<input class="input mt-1" name="location"></label><label class="block text-xs text-zinc-400">Work mode<select class="input mt-1" name="work_mode"><option value="">Not specified</option><option>Remote</option><option>Hybrid</option><option>On-site</option></select></label><label class="block text-xs text-zinc-400">Job link<input class="input mt-1" type="url" name="job_url" placeholder="https://"></label><label class="block text-xs text-zinc-400">Applied date<input class="input mt-1" type="date" name="applied_at"></label><label class="block text-xs text-zinc-400">Notes<textarea class="input mt-1 h-24" name="notes"></textarea></label><button class="btn btn-primary w-full">Save application</button></form></aside><div class="space-y-3">@forelse($jobs as $job)<article class="card p-5"><div class="flex flex-wrap justify-between gap-3"><div><h2 class="font-semibold">{{ $job->role }}</h2><p class="mt-1 text-sm text-zinc-400">{{ $job->company }}{{ $job->location ? ' · '.$job->location : '' }}</p></div><span class="rounded-full bg-cyan-400/10 px-3 py-1 text-xs capitalize text-cyan-200">{{ $job->status }}</span></div>@if($job->notes)<p class="mt-4 text-sm leading-6 text-zinc-400">{{ $job->notes }}</p>@endif<div class="mt-4 flex flex-wrap gap-2"><form method="POST" action="{{ route('jobs.update', $job) }}" class="flex gap-2">@csrf @method('PATCH')<select class="input !w-auto !py-2 text-xs" name="status">@foreach(['saved','applied','interviewing','offer','rejected','withdrawn'] as $status)<option value="{{ $status }}" @selected($job->status === $status)>{{ ucfirst($status) }}</option>@endforeach</select><button class="btn btn-secondary">Update</button></form>@if($job->job_url)<a class="btn btn-secondary" href="{{ $job->job_url }}" target="_blank" rel="noreferrer">Open posting</a>@endif<form method="POST" action="{{ route('jobs.destroy', $job) }}" onsubmit="return confirm('Remove this application?')">@csrf @method('DELETE')<button class="btn border border-rose-400/25 text-rose-200">Remove</button></form></div></article>@empty<div class="card border-dashed p-10 text-center text-sm text-zinc-400">No applications yet. Add your first real opportunity on the left.</div>@endforelse</div></section>

      @elseif($screen === 'interviews')
        <section class="mt-7 grid gap-5 xl:grid-cols-[.72fr_1.28fr]"><aside class="card h-max p-5"><h2 class="font-semibold">Plan practice</h2><form method="POST" action="{{ route('interviews.store') }}" class="mt-5 space-y-3">@csrf<label class="block text-xs text-zinc-400">Session title<input class="input mt-1" name="title" placeholder="Technical practice" required></label><label class="block text-xs text-zinc-400">Target role<input class="input mt-1" name="target_role" value="{{ auth()->user()->target_role }}"></label><label class="block text-xs text-zinc-400">Focus<select class="input mt-1" name="session_type"><option value="general">General</option><option value="technical">Technical</option><option value="behavioral">Behavioral</option></select></label><label class="block text-xs text-zinc-400">Minutes<input class="input mt-1" type="number" min="5" max="180" name="duration_minutes" value="30"></label><label class="block text-xs text-zinc-400">Related application<select class="input mt-1" name="job_application_id"><option value="">None</option>@foreach($jobs as $job)<option value="{{ $job->id }}">{{ $job->company }} — {{ $job->role }}</option>@endforeach</select></label><button class="btn btn-primary w-full">Create session</button></form></aside><div class="space-y-3">@forelse($interviews as $interview)<article class="card p-5"><div class="flex justify-between gap-4"><div><h2 class="font-semibold">{{ $interview->title }}</h2><p class="mt-1 text-sm text-zinc-400 capitalize">{{ $interview->session_type ?? $interview->type ?? 'general' }} · {{ $interview->duration_minutes ?? 0 }} minutes</p></div><span class="rounded-full bg-white/[.06] px-3 py-1 text-xs capitalize">{{ $interview->status }}</span></div><div class="mt-4 flex flex-wrap gap-2">@if($interview->status !== 'completed')<form method="POST" action="{{ route('interviews.complete', $interview) }}" class="flex gap-2">@csrf @method('PATCH')<input class="input !w-24 !py-2 text-xs" type="number" min="0" max="100" name="score" placeholder="Score"><button class="btn btn-primary">Mark complete</button></form>@endif<form method="POST" action="{{ route('interviews.destroy', $interview) }}" onsubmit="return confirm('Remove this session?')">@csrf @method('DELETE')<button class="btn border border-rose-400/25 text-rose-200">Remove</button></form></div></article>@empty<div class="card border-dashed p-10 text-center text-sm text-zinc-400">No interview practice saved yet. Create a session to begin.</div>@endforelse</div></section>

      @elseif($screen === 'skills')
        <section class="mt-7 grid gap-5 xl:grid-cols-[.72fr_1.28fr]"><aside class="card h-max p-5"><h2 class="font-semibold">Add a skill</h2><form method="POST" action="{{ route('skills.store') }}" class="mt-5 space-y-3">@csrf<label class="block text-xs text-zinc-400">Skill<input class="input mt-1" name="name" required></label><label class="block text-xs text-zinc-400">Category<input class="input mt-1" name="category" placeholder="Technical, communication, design"></label><label class="block text-xs text-zinc-400">Current proficiency (0–100)<input class="input mt-1" type="number" min="0" max="100" name="proficiency"></label><label class="block text-xs text-zinc-400">Years of experience<input class="input mt-1" type="number" step="0.5" min="0" name="years_experience"></label><label class="flex gap-2 text-xs text-zinc-300"><input type="checkbox" name="is_priority" value="1"> Make this a priority</label><label class="block text-xs text-zinc-400">Evidence<textarea class="input mt-1 h-20" name="evidence" placeholder="A project, certificate, or outcome"></textarea></label><button class="btn btn-primary w-full">Save skill</button></form></aside><div class="grid gap-3 md:grid-cols-2">@forelse($skills as $skill)<article class="card p-5"><div class="flex justify-between gap-3"><div><h2 class="font-semibold">{{ $skill->name }}</h2><p class="mt-1 text-xs text-zinc-500">{{ $skill->category ?: 'Uncategorised' }}</p></div>@if($skill->is_priority)<span class="text-xs text-cyan-200">PRIORITY</span>@endif</div><div class="mt-5 h-2 overflow-hidden rounded-full bg-white/[.07]"><div class="h-full rounded-full bg-gradient-to-r from-violet-400 to-cyan-300" style="width: {{ min(100, (int) ($skill->proficiency ?? 0)) }}%"></div></div><p class="mt-2 text-xs text-zinc-400">{{ $skill->proficiency ?? 0 }}% · {{ $skill->years_experience ?? 0 }} years</p>@if($skill->evidence)<p class="mt-4 text-sm text-zinc-400">{{ $skill->evidence }}</p>@endif<form method="POST" action="{{ route('skills.destroy', $skill) }}" class="mt-4" onsubmit="return confirm('Remove this skill?')">@csrf @method('DELETE')<button class="text-xs text-rose-200">Remove skill</button></form></article>@empty<div class="card border-dashed p-10 text-center text-sm text-zinc-400 md:col-span-2">No skills saved yet. Add skills based on work you can honestly show.</div>@endforelse</div></section>

      @elseif($screen === 'insights')
        <section class="mt-7 grid gap-5 xl:grid-cols-[.72fr_1.28fr]"><aside class="card h-max p-5"><h2 class="font-semibold">Add career goal</h2><form method="POST" action="{{ route('goals.store') }}" class="mt-5 space-y-3">@csrf<label class="block text-xs text-zinc-400">Goal<input class="input mt-1" name="title" placeholder="Move into a product analyst role" required></label><label class="block text-xs text-zinc-400">Target role<input class="input mt-1" name="target_role"></label><label class="block text-xs text-zinc-400">Target date<input class="input mt-1" type="date" name="target_date"></label><label class="block text-xs text-zinc-400">Starting progress<input class="input mt-1" type="number" min="0" max="100" name="progress" value="0"></label><label class="block text-xs text-zinc-400">Why it matters<textarea class="input mt-1 h-24" name="motivation"></textarea></label><button class="btn btn-primary w-full">Save goal</button></form></aside><div class="space-y-3">@forelse($goals as $goal)<article class="card p-5"><div class="flex justify-between gap-4"><div><h2 class="font-semibold">{{ $goal->title }}</h2><p class="mt-1 text-sm text-zinc-400">{{ $goal->target_role ?: 'Career goal' }}{{ $goal->target_date ? ' · target '.$goal->target_date->format('M j, Y') : '' }}</p></div><span class="text-lg font-semibold text-cyan-200">{{ $goal->progress }}%</span></div><div class="mt-4 h-2 overflow-hidden rounded-full bg-white/[.07]"><div class="h-full rounded-full bg-gradient-to-r from-violet-400 to-cyan-300" style="width: {{ $goal->progress }}%"></div></div>@if($goal->motivation)<p class="mt-4 text-sm text-zinc-400">{{ $goal->motivation }}</p>@endif<div class="mt-4 flex gap-2"><form method="POST" action="{{ route('goals.update', $goal) }}" class="flex gap-2">@csrf @method('PATCH')<input class="input !w-24 !py-2 text-xs" type="number" min="0" max="100" name="progress" value="{{ $goal->progress }}"><button class="btn btn-secondary">Update</button></form><form method="POST" action="{{ route('goals.destroy', $goal) }}" onsubmit="return confirm('Remove this goal?')">@csrf @method('DELETE')<button class="btn border border-rose-400/25 text-rose-200">Remove</button></form></div></article>@empty<div class="card border-dashed p-10 text-center text-sm text-zinc-400">No goals saved yet. A clear target makes the rest of your workspace more useful.</div>@endforelse</div></section>

      @elseif($screen === 'portfolio')
        <section class="mt-7 grid gap-5 xl:grid-cols-[.72fr_1.28fr]"><aside class="card h-max p-5"><h2 class="font-semibold">Add a project</h2><form method="POST" action="{{ route('portfolio.store') }}" class="mt-5 space-y-3">@csrf<label class="block text-xs text-zinc-400">Project title<input class="input mt-1" name="title" required></label><label class="block text-xs text-zinc-400">Short description<input class="input mt-1" name="tagline"></label><label class="block text-xs text-zinc-400">Your role<input class="input mt-1" name="role"></label><label class="block text-xs text-zinc-400">Description<textarea class="input mt-1 h-28" name="description"></textarea></label><label class="block text-xs text-zinc-400">Live project link<input class="input mt-1" type="url" name="project_url" placeholder="https://"></label><label class="block text-xs text-zinc-400">Repository link<input class="input mt-1" type="url" name="repository_url" placeholder="https://"></label><button class="btn btn-primary w-full">Save project</button></form></aside><div class="grid gap-3 md:grid-cols-2">@forelse($projects as $project)<article class="card p-5"><h2 class="font-semibold">{{ $project->title }}</h2><p class="mt-1 text-xs text-cyan-200">{{ $project->role ?: 'Project' }}</p><p class="mt-4 text-sm leading-6 text-zinc-400">{{ $project->description ?: $project->tagline ?: 'No description added yet.' }}</p><div class="mt-5 flex flex-wrap gap-3 text-xs"><a href="{{ $project->project_url }}" class="{{ $project->project_url ? 'text-cyan-200' : 'pointer-events-none text-zinc-600' }}" target="_blank" rel="noreferrer">Live project</a><a href="{{ $project->repository_url ?? $project->github_url }}" class="{{ ($project->repository_url ?? $project->github_url) ? 'text-cyan-200' : 'pointer-events-none text-zinc-600' }}" target="_blank" rel="noreferrer">Repository</a><form method="POST" action="{{ route('portfolio.destroy', $project) }}" onsubmit="return confirm('Remove this project?')">@csrf @method('DELETE')<button class="text-rose-200">Remove</button></form></div></article>@empty<div class="card border-dashed p-10 text-center text-sm text-zinc-400 md:col-span-2">No portfolio projects yet. Add work you are proud to discuss in an interview.</div>@endforelse</div></section>

      @elseif(in_array($screen, ['dashboard', 'analytics'], true))
        <section class="mt-7 space-y-5"><div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">@foreach([['Applications', $metrics['applications']], ['Active applications', $metrics['active']], ['Interview sessions', $metrics['interviews']], ['Completed sessions', $metrics['completed_interviews']], ['Skills tracked', $metrics['skills']], ['Portfolio projects', $metrics['projects']]] as [$label, $value])<article class="card p-5"><p class="text-sm text-zinc-400">{{ $label }}</p><p class="mt-3 text-4xl font-semibold">{{ $value }}</p></article>@endforeach</div><article class="card p-6"><h2 class="font-semibold">Applications by status</h2><div class="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">@forelse($jobStatuses as $status => $count)<div class="rounded-xl border border-white/[.08] p-4"><p class="capitalize text-zinc-400">{{ $status ?: 'Unspecified' }}</p><p class="mt-2 text-2xl font-semibold">{{ $count }}</p></div>@empty<p class="text-sm text-zinc-400">Save job applications to see real progress data here.</p>@endforelse</div></article></section>

      @else
        <section class="mt-7 max-w-3xl"><article class="card p-6"><h2 class="font-semibold">Professional profile</h2><form method="POST" action="{{ route('profile.update') }}" class="mt-5 grid gap-4 sm:grid-cols-2">@csrf @method('PATCH')<label class="text-xs text-zinc-400">Name<input class="input mt-1" name="name" value="{{ old('name', auth()->user()->name) }}" required></label><label class="text-xs text-zinc-400">Headline<input class="input mt-1" name="headline" value="{{ old('headline', $profile?->headline) }}" placeholder="e.g. Junior product designer"></label><label class="text-xs text-zinc-400">Location<input class="input mt-1" name="location" value="{{ old('location', $profile?->location) }}"></label><label class="text-xs text-zinc-400">LinkedIn URL<input class="input mt-1" type="url" name="linkedin_url" value="{{ old('linkedin_url', $profile?->linkedin_url) }}"></label><label class="text-xs text-zinc-400 sm:col-span-2">Website URL<input class="input mt-1" type="url" name="website_url" value="{{ old('website_url', $profile?->website_url) }}"></label><label class="text-xs text-zinc-400 sm:col-span-2">About<textarea class="input mt-1 h-32" name="about">{{ old('about', $profile?->about) }}</textarea></label><label class="flex items-center gap-2 text-sm text-zinc-300 sm:col-span-2"><input type="checkbox" name="available_for_work" value="1" @checked(old('available_for_work', $profile?->available_for_work))> Open to work</label><button class="btn btn-primary sm:col-span-2">{{ $screen === 'settings' ? 'Save settings' : 'Save profile' }}</button></form></article></section>
      @endif
    </main>
  </div>
</div>
</body>
</html>
