<!doctype html>
<html lang="en" class="dark">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{{ $letter ? 'Edit cover letter' : 'Create cover letter' }} · SmartCV</title>
  @vite(['resources/css/app.css', 'resources/js/app.js'])
</head>
<body class="min-h-screen bg-[#070b18] text-zinc-100">
  <header class="sticky top-0 z-20 border-b border-white/[.08] bg-[#090e20]/95 backdrop-blur"><div class="mx-auto flex max-w-7xl items-center justify-between gap-4 px-5 py-4 sm:px-8"><a href="{{ route('cover-letters.index') }}" class="text-sm font-semibold text-zinc-300">← Cover letters</a><div class="flex gap-2">@if($letter)<a href="{{ route('cover-letters.preview', $letter) }}" target="_blank" class="btn btn-secondary">Preview / PDF</a><a href="{{ route('cover-letters.download.docx', $letter) }}" class="btn btn-secondary">Export DOCX</a>@endif</div></div></header>
  <main class="mx-auto max-w-7xl px-5 py-8 sm:px-8">
    <div class="mb-7"><p class="eyebrow">Cover letter builder</p><h1 class="mt-2 text-3xl font-semibold tracking-tight">{{ $letter ? $letter->title : 'Build a letter for a real opportunity' }}</h1><p class="mt-2 text-sm text-zinc-400">Use a clear story: why this role, proof of relevant work, and a confident next step.</p></div>
    @if(session('status'))<div class="mb-5 rounded-xl border border-emerald-400/25 bg-emerald-400/10 p-4 text-sm text-emerald-100">{{ session('status') }}</div>@endif
    @if($errors->any())<div class="mb-5 rounded-xl border border-rose-400/25 bg-rose-400/10 p-4 text-sm text-rose-100"><ul class="list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    <form method="POST" action="{{ $letter ? route('cover-letters.update', $letter) : route('cover-letters.store') }}" class="grid gap-5 xl:grid-cols-[minmax(0,1fr)_320px]">@csrf @if($letter) @method('PATCH') @endif
      <div class="space-y-5">
        <section class="card p-5 sm:p-6"><p class="eyebrow">Opportunity</p><div class="mt-5 grid gap-4 sm:grid-cols-2"><label class="text-xs text-zinc-400 sm:col-span-2">Letter name<input name="title" class="input mt-1" required value="{{ old('title', $letter?->title) }}" placeholder="Product designer — Acme"></label><label class="text-xs text-zinc-400">Related job application<select name="job_application_id" class="input mt-1"><option value="">Not linked yet</option>@foreach($jobs as $job)<option value="{{ $job->id }}" @selected(old('job_application_id', $letter?->job_application_id) == $job->id)>{{ $job->company }} — {{ $job->role }}</option>@endforeach</select></label><label class="text-xs text-zinc-400">Resume used<select name="resume_id" class="input mt-1"><option value="">Not linked yet</option>@foreach($resumes as $resume)<option value="{{ $resume->id }}" @selected(old('resume_id', $letter?->resume_id) == $resume->id)>{{ $resume->name }}{{ $resume->is_primary ? ' · Primary' : '' }}</option>@endforeach</select></label><label class="text-xs text-zinc-400">Company<input name="company_name" class="input mt-1" value="{{ old('company_name', $letter?->company_name) }}" placeholder="Acme Inc."></label><label class="text-xs text-zinc-400">Job title<input name="job_title" class="input mt-1" value="{{ old('job_title', $letter?->job_title) }}" placeholder="Product Designer"></label><label class="text-xs text-zinc-400">Hiring manager / team<input name="recipient_name" class="input mt-1" value="{{ old('recipient_name', $letter?->recipient_name) }}" placeholder="Hiring Manager"></label><label class="text-xs text-zinc-400">Subject line<input name="subject" class="input mt-1" value="{{ old('subject', $letter?->subject) }}" placeholder="Application for Product Designer"></label></div></section>
        <section class="card p-5 sm:p-6"><p class="eyebrow">Your message</p><div class="mt-5 space-y-4"><label class="block text-xs text-zinc-400">Opening<textarea name="opening" class="input mt-1 h-24 resize-y" placeholder="Dear Hiring Manager,">{{ old('opening', $letter?->opening ?? 'Dear Hiring Manager,') }}</textarea></label><label class="block text-xs text-zinc-400">Main letter <span class="text-rose-300">required</span><textarea name="body" class="input mt-1 h-72 resize-y" required placeholder="Explain why you want this role. Use specific work, outcomes, and skills that match the opportunity.">{{ old('body', $letter?->body) }}</textarea></label><label class="block text-xs text-zinc-400">Closing<textarea name="closing" class="input mt-1 h-24 resize-y" placeholder="Thank you for your time and consideration.">{{ old('closing', $letter?->closing ?? 'Thank you for your time and consideration.') }}</textarea></label><label class="block text-xs text-zinc-400">Your sign-off name<input name="signature_name" class="input mt-1" value="{{ old('signature_name', $letter?->signature_name ?? auth()->user()->name) }}"></label></div></section>
      </div>
      <aside class="space-y-5"><section class="card sticky top-24 p-5"><p class="eyebrow">Letter controls</p><h2 class="mt-1 text-lg font-semibold">Tailor with intent</h2><label class="mt-5 block text-xs text-zinc-400">Template<select name="template" class="input mt-1">@foreach($templates as $value => $label)<option value="{{ $value }}" @selected(old('template', $letter?->template ?? 'modern') === $value)>{{ $label }}</option>@endforeach</select></label><label class="mt-4 block text-xs text-zinc-400">Status<select name="status" class="input mt-1"><option value="draft" @selected(old('status', $letter?->status ?? 'draft') === 'draft')>Draft</option><option value="ready" @selected(old('status', $letter?->status) === 'ready')>Ready to send</option></select></label><div class="mt-5 rounded-xl border border-cyan-400/20 bg-cyan-400/[.06] p-4 text-xs leading-5 text-zinc-300">Keep it truthful. A strong cover letter connects evidence from your actual experience to the role — it does not repeat your resume.</div><button class="btn btn-primary mt-5 w-full">{{ $letter ? 'Save cover letter' : 'Create cover letter' }}</button>@if($letter)<a href="{{ route('cover-letters.download.txt', $letter) }}" class="btn btn-secondary mt-2 w-full">Download TXT</a><form method="POST" action="{{ route('cover-letters.duplicate', $letter) }}" class="mt-2">@csrf<button class="btn btn-secondary w-full">Duplicate for another role</button></form>@endif</section></aside>
    </form>
  </main>
</body>
</html>
