<!doctype html>
<html lang="en" class="dark">
<head>
    <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Learning Paths · SmartCV</title>@vite(['resources/css/app.css', 'resources/js/app.js'])
</head>
<body class="min-h-screen bg-[#070b18] text-zinc-100">
<div class="min-h-screen">
    <x-workspace-sidebar active-screen="learning-paths" />
    <div class="min-h-screen lg:pl-64">
        <header class="sticky top-0 z-20 flex items-center justify-between border-b border-white/[.07] bg-[#090e20]/95 px-5 py-4 backdrop-blur lg:px-9"><a href="{{ route('dashboard') }}" class="font-bold lg:hidden">SMART<span class="text-violet-300">CV</span></a><p class="hidden text-sm text-zinc-500 sm:block">Your private career growth plan</p><a href="{{ route('profile') }}" class="flex items-center gap-2 text-sm font-medium"><span class="grid h-9 w-9 place-items-center rounded-full bg-gradient-to-br from-violet-400 to-cyan-300 text-slate-950">{{ strtoupper(substr(auth()->user()->name, 0, 1)) }}</span>{{ auth()->user()->name }}</a></header>
        <main class="mx-auto max-w-7xl px-5 py-8 lg:px-9">
            <p class="eyebrow">Career intelligence</p><div class="mt-2 flex flex-wrap items-end justify-between gap-4"><div><h1 class="text-3xl font-semibold">Learning paths</h1><p class="mt-2 max-w-2xl text-sm leading-6 text-zinc-400">Describe your real goal and SmartCV will use Groq to create a goal-specific plan. It ignores unrelated old job-match gaps.</p></div><a href="{{ route('insights') }}" class="btn btn-secondary">Manage career goals</a></div>
            @if(session('status'))<div class="mt-6 rounded-xl border border-emerald-400/25 bg-emerald-400/10 p-4 text-sm text-emerald-100">{{ session('status') }}</div>@endif
            @if($errors->any())<div class="mt-6 rounded-xl border border-rose-400/25 bg-rose-400/10 p-4 text-sm text-rose-100">@foreach($errors->all() as $error)<p>{{ $error }}</p>@endforeach</div>@endif
            <section class="mt-7 grid gap-5 xl:grid-cols-[.78fr_1.22fr]">
                <aside class="card h-max p-5"><p class="eyebrow">Build a personalised plan</p><h2 class="mt-2 text-lg font-semibold">Tell SmartCV what you actually want</h2><p class="mt-3 text-sm leading-6 text-zinc-400">Your written goal is the main instruction. Old technical job gaps will not be used for an entrepreneurship or business goal.</p><form method="POST" action="{{ route('learning-paths.store') }}" class="mt-5 space-y-3">@csrf<label class="block text-xs text-zinc-400">What do you want to achieve?<textarea class="input mt-1 h-28" name="goal" required minlength="20" placeholder="I want to become an entrepreneur and validate a small software business for local shops.">{{ old('goal') }}</textarea></label><label class="block text-xs text-zinc-400">Plan name <span class="text-zinc-600">(optional)</span><input class="input mt-1" name="title" value="{{ old('title') }}" placeholder="My entrepreneurship plan"></label><label class="block text-xs text-zinc-400">Target role <span class="text-zinc-600">(optional)</span><input class="input mt-1" name="target_role" value="{{ old('target_role') }}" placeholder="Entrepreneur, Product Manager, Designer..."></label><button class="btn btn-primary w-full">Create AI learning path</button></form><div class="mt-5 border-t border-white/[.07] pt-4"><p class="text-xs font-semibold text-zinc-200">How it works</p><p class="mt-2 text-xs leading-5 text-zinc-400">Groq uses your written goal first, then only relevant saved skills and job-match data. It creates a fresh plan every time.</p></div></aside>
                <div class="space-y-4">@forelse($paths as $path)@php($completed = $path->items->where('status', 'completed')->count())@php($total = $path->items->count())@php($progress = $total ? (int) round(($completed / $total) * 100) : 0)<article class="card p-5 sm:p-6"><div class="flex flex-wrap justify-between gap-4"><div><p class="text-xs uppercase tracking-[.14em] text-cyan-200">{{ $path->target_role ?: 'Career growth' }}</p><h2 class="mt-2 text-xl font-semibold">{{ $path->title }}</h2><p class="mt-2 max-w-2xl text-sm leading-6 text-zinc-400">{{ $path->summary }}</p></div><form method="POST" action="{{ route('learning-paths.destroy', $path) }}" onsubmit="return confirm('Remove this learning path?')">@csrf @method('DELETE')<button class="text-xs text-rose-200">Remove plan</button></form></div><div class="mt-5"><div class="mb-2 flex justify-between text-xs text-zinc-400"><span>{{ $completed }} of {{ $total }} steps complete</span><span class="text-cyan-200">{{ $progress }}%</span></div><progress class="h-2 w-full overflow-hidden rounded-full accent-cyan-300" value="{{ $progress }}" max="100">{{ $progress }}%</progress></div><div class="mt-6 space-y-3">@forelse($path->items as $item)<div class="rounded-xl border border-white/[.08] bg-white/[.02] p-4"><div class="flex flex-wrap justify-between gap-3"><div><p class="text-xs font-semibold uppercase tracking-[.13em] text-violet-200">{{ $item->skill_name }}</p><h3 class="mt-1 font-semibold">{{ $item->title }}</h3><p class="mt-2 text-sm leading-6 text-zinc-400">{{ $item->description }}</p><p class="mt-3 text-xs text-zinc-500">About {{ $item->estimated_hours ?: 4 }} focused hours</p></div><form method="POST" action="{{ route('learning-path-items.update', $item) }}" class="flex h-max items-center gap-2">@csrf @method('PATCH')<select class="input !w-auto !py-2 text-xs" name="status"><option value="planned" @selected($item->status === 'planned')>Planned</option><option value="in_progress" @selected($item->status === 'in_progress')>In progress</option><option value="completed" @selected($item->status === 'completed')>Completed</option></select><button class="btn btn-secondary">Save</button></form></div></div>@empty<p class="rounded-xl border border-dashed border-white/[.1] p-5 text-sm text-zinc-500">This plan has no steps yet.</p>@endforelse</div></article>@empty<div class="card border-dashed p-10 text-center"><span class="grid mx-auto h-12 w-12 place-items-center rounded-2xl bg-cyan-400/10 text-xl text-cyan-200">✦</span><h2 class="mt-4 font-semibold">Your next steps will appear here.</h2><p class="mx-auto mt-2 max-w-md text-sm leading-6 text-zinc-400">Create a path from the left. The plan uses only your saved SmartCV information and remains private to your account.</p></div>@endforelse</div>
            </section>
        </main>
    </div>
</div>
</body>
</html>
